### ISSUE TITLE
Switch from using if/else to switch statement for readability

### ISSUE THREAD

**Issue by sikofitt** [sikofitt/RenegadeBBS#1]
Right now there are a lot of if/else branches here.  A case statement makes more sense for usability and readability.

https://github.com/sikofitt/RenegadeBBS/blob/8d6d58ee33adcff0c96913e68fca8963211a6cce/SOURCE/RGLNG.PAS#L119

**Comment by leewoodridge** [comment]
Absolutely. We're currently compiling with BP, which doesn't support strings in a case statement. We would need to update the code so we can use FPC for this.

**Comment by sikofitt** [comment]
Oops, you are absolutely right.  Completely forgot about that limitation.  I wonder how much work it would be to get it to compile with the msdos target of fpc with TP mode enabled.
